In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from subprocess import check_output
from sklearn import linear_model

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier



from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [ ]:
meta_data = pd.read_csv("/content/drive/MyDrive/Datasets for ML/PS_20174392719_1491204439457_log.csv")

In [ ]:
del meta_data['nameDest']
del meta_data['nameOrig']
del meta_data['type']
len(meta_data)

6362620

In [ ]:
Cols = meta_data[['step','amount','oldbalanceOrg','newbalanceOrig','oldbalanceDest','newbalanceDest','isFlaggedFraud']]
y = meta_data['isFraud']
X = Cols


In [ ]:
meta_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 8 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   amount          float64
 2   oldbalanceOrg   float64
 3   newbalanceOrig  float64
 4   oldbalanceDest  float64
 5   newbalanceDest  float64
 6   isFraud         int64  
 7   isFlaggedFraud  int64  
dtypes: float64(5), int64(3)
memory usage: 388.3 MB


In [ ]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42) #use this random state to match my results only
#training our model

In [ ]:
logitic = linear_model.LogisticRegression()
model = logitic.fit(X_train,y_train)
predictions = model.predict(X_test)


In [ ]:


print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)



              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1906351
           1       0.37      0.43      0.40      2435

    accuracy                           1.00   1908786
   macro avg       0.68      0.72      0.70   1908786
weighted avg       1.00      1.00      1.00   1908786

[[1904535    1816]
 [   1380    1055]]


0.9983256373422689

In [ ]:
gnb = GaussianNB()
model = gnb.fit(X_train,y_train)
predictions = model.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))
accuracy_score(y_test,predictions)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00   1906351
           1       0.03      0.16      0.05      2435

    accuracy                           0.99   1908786
   macro avg       0.51      0.58      0.52   1908786
weighted avg       1.00      0.99      0.99   1908786

[[1893838   12513]
 [   2043     392]]


0.9923742106239254

In [ ]:
clf=RandomForestClassifier(n_estimators=25) 
model = clf.fit(X_train,y_train)
#predicting our labels
predictions = model.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))
accuracy_score(y_test,predictions)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1906351
           1       0.95      0.72      0.82      2435

    accuracy                           1.00   1908786
   macro avg       0.98      0.86      0.91   1908786
weighted avg       1.00      1.00      1.00   1908786

[[1906263      88]
 [    687    1748]]


0.9995939827722962

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
print(meta_data.shape)
print(meta_data.head())

(6362620, 8)
   step    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1   9839.64       170136.0       160296.36             0.0   
1     1   1864.28        21249.0        19384.72             0.0   
2     1    181.00          181.0            0.00             0.0   
3     1    181.00          181.0            0.00         21182.0   
4     1  11668.14        41554.0        29885.86             0.0   

   newbalanceDest  isFraud  isFlaggedFraud  
0             0.0        0               0  
1             0.0        0               0  
2             0.0        1               0  
3             0.0        1               0  
4             0.0        0               0  
